### ISSUE TITLE
Request for $order object filter during payment process and ipn response 

### ISSUE THREAD

**Issue by abdusfauzi** [Billplz/Billplz-for-WooCommerce#10]
I would like to request for `$order` object filter between line `417-418` (before line `418`) and line `499-500` (before line `500`).

Suggestion `apply_filters`:

`$order = apply_filters( 'bfw_filter_name_here', $order );`

There is a use case where, I want to apply _soft discount_ for those who pay using Billplz. Such discount won't be record/save into Order database due to cases where user might click to pay with Billplz, but later cancel.

Therefore, a filter can amend the `$order` object, add a discount, then update with new **total**. Next, these values will be extracted to create new Billplz's bill.

https://github.com/Billplz/Billplz-for-WooCommerce/blob/03ca4f2d0fa8888720fa63e3c2ff389a912826c3/billplzWoo.php#L417-L418

As for a filter before line `500`, it is use to re-implement the alteration or discount again after the payment was successful, and this time the amended value will be recorded with `$order->save()`. Thus, record the final amount of the discount into the Order. Perhaps, the filter include a variable mentioning `paid`.

https://github.com/Billplz/Billplz-for-WooCommerce/blob/03ca4f2d0fa8888720fa63e3c2ff389a912826c3/billplzWoo.php#L499-L500

**Comment by wzul** [comment]
Considering if there's a case where unpaid bill also requires filter, I believe we should put the filter before `if ($rbody['paid']) {` and pass the Billplz `$rbody` var to allow filter determine the payment status.

**Comment by wzul** [comment]
Commited

https://github.com/Billplz/Billplz-for-WooCommerce/commit/2856e3ebf19f92fe4b7ed5802ff6ff2ae0c1dd30

**Comment by abdusfauzi** [comment]
@wzul maybe. nice touch with the `$rbody`. Then, we can use the value of `$rbody` to create our own "logic". Awesome.

**Comment by wzul** [comment]
Ok. will push to update soon

**Comment by abdusfauzi** [comment]
@wzul Nice! need to get this update a.s.a.p because i'm using the filter by coming Monday. thanks @wzul

**Comment by wzul** [comment]
Pushed!

**Comment by abdusfauzi** [comment]
@wzul superb!
