### ISSUE TITLE
Fatal error: Uncaught ArgumentCountError: Too few arguments to function for bfw_filter_order

### ISSUE THREAD

**Issue by abdusfauzi** [Billplz/Billplz-for-WooCommerce#11]
Got this error for this line:

`Fatal error: Uncaught ArgumentCountError: Too few arguments to function loe_billplz_payment_filter_order(), 1 passed in /Users/abdusfauzi/Sites/vhosts/littleones/web/wp/wp-includes/class-wp-hook.php on line 286 and exactly 2 expected in...`

which reflect this line:

https://github.com/Billplz/Billplz-for-WooCommerce/blob/4e23a83ce463a035d587cba7d06003d296a8a727/billplzWoo.php#L420

Because the other filter, with same name requesting 2 variables. My function was created with 2 variables supplied.

```
function billplz_payment_filter_order( $order, $rbody ) {
	$discount = get_post_meta( $order->get_id(), '_cart_discount', true );
                
    if ( empty( $discount ) ) {
        $multiplier = 0;
        $items      = $order->get_items();

        foreach ( $items as $item_id => $product ) {
            $product = $product->get_product();

            if ( has_term( 'monthly', 'product_tag', $product->get_id() ) ) {
                $multiplier++;
            }
        }

        if ( 0 < $multiplier ) {
            $discount = 10 * $multiplier;

            $order->set_discount_total( $discount );
            $order->set_total( $order->get_total() - $discount );

            if ( ! empty( $rbody ) && $rbody['paid'] ) {
	            $order->save();
            }
        }
    }

    return $order;
}
```

Perhaps, we need 2 different filter naming

**Comment by wzul** [comment]
What you think if we make the last receiving parameter as optional argument.

`function billplz_payment_filter_order( $order, $rbody = false) {`?

**Comment by abdusfauzi** [comment]
@wzul make it empty array better? because the expected data will be array type? we can check it with `if ( ! empty( $rbody ) ) {...}`.

**Comment by wzul** [comment]
ok. will pass the empty array for that

**Comment by abdusfauzi** [comment]
@wzul nice.

> ok. will pass the empty array for that

**Comment by wzul** [comment]
Pushed!

**Comment by abdusfauzi** [comment]
@wzul tested and working so far. Will close this issue.
