### ISSUE TITLE
Discussion: to save or not to save billplz ID and payment method if user cancel payment on Billplz page

### ISSUE THREAD

**Issue by abdusfauzi** [Billplz/Billplz-for-WooCommerce#12]
As per issue title, I faced an issue where few users cancelled their payment or close the page when they reached Billplz payment page. 

However, from backend, the payment method has been recorded as **billplz**, mean while no payment was made. This give a false-positive of payment has been `completed`. There are few cases where I wanted to filter Orders by payment method, and this would include the `pending` Orders too.

I believe, we should not record/save the payment method into the Order if the payment is not success. This open the Order for other method of payment.

However, previously I suggested we save the bill id into `_transaction_id` to be used again when user want to re-query or re-visit Billplz payment page. Does this affect anything if we just record billplz id, but do not save payment method? Or do we need to use temporary `post_meta` before migrate the billplz id to `_transaction_id`?

**Comment by wzul** [comment]
That's already being done before issue #6 (use temporary post_meta and only store the id after making payment). (please ignore the bill url and consider it as bill id)

Regarding on _transaction_id, I don't see reason why it should be false positive because we have `post_status` that can indicate the current order status.

**Comment by abdusfauzi** [comment]
Correct. But i keep on getting questions from “non-tech-admin” about that. 😅

No worries, not a serious issue.
