### ISSUE TITLE
Uncaught Exception: X Signature Calculation Mismatch

### ISSUE THREAD

**Issue by abdusfauzi** [Billplz/Billplz-for-WooCommerce#13]
Just found this error in my log. I guess, it is because Billplz verification also use the `Order value` as one of the key when comparing the calculation.
Updated

I have implemented a feature to manipulate discount on the fly, just before they click to pay. This discount however is not save and updated into the database. Therefore, when the algorithm wants to compare, the amount is different, therefore the hash is different. The discount will only be implemented if the payment is `paid`.

```
PHP Fatal error:  Uncaught Exception: X Signature Calculation Mismatch! in /web/app/plugins/billplz-for-woocommerce/includes/Billplz_WPConnect.php:326
Stack trace:
#0 /web/app/plugins/billplz-for-woocommerce/billplzWoo.php(496): BillplzWooCommerceWPConnect::getXSignature('S-itLjHIiz8M98p...')
#1 /web/wp/wp-includes/class-wp-hook.php(286): WC_Billplz_Gateway->check_ipn_response('')
#2 /web/wp/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#3 /web/wp/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /web/app/plugins/woocommerce/includes/class-wc-api.php(97): do_action('woocommerce_api...')
#5 /web/wp/wp-includes/class-wp-hook.php(286): WC_API->handle_api_requests(Object(WP))
#6 /web/wp/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#7 /web/app/plugins/billplz-for-woocommerce/includes/Billplz_WPConnect.php on line 326
```

Suggested issue line. The `$singing` value is incorrect because during verification, the `Order` is not yet updated with the discount. Any idea to solve this?

Or, the value that will be compare is just between passed value from Billplz server and the value on Billplz server?

https://github.com/Billplz/Billplz-for-WooCommerce/blob/231827a6925af9d9037276a744740a6c8a287f3e/includes/Billplz_WPConnect.php#L319

**Comment by wzul** [comment]
The value that will be compared is just between the passed value from Billplz server. 

It should not related to value stored in local db. 

Confirm the x signature key is correct?

**Comment by abdusfauzi** [comment]
@wzul hm. what would be the problem then. 🤔I think the callback is still working fine, because the Orders are getting completed and paid notes are recorded.

**Comment by wzul** [comment]
Same as redirect. All data is verified from $_GET

https://github.com/Billplz/Billplz-for-WooCommerce/blob/231827a6925af9d9037276a744740a6c8a287f3e/includes/Billplz_WPConnect.php#L273

**Comment by abdusfauzi** [comment]
Maybe I need to dump the $_GET to make sure data is correct as required to create signature comparison. Will get back. 👌🏻

**Comment by abdusfauzi** [comment]
Forgotten about this bug. Closing ticket for now.
