### ISSUE TITLE
BillPlz WP Plugin not support new WooCommerce HPOS features.

### ISSUE THREAD

**Issue by msulaimanmisri** [Billplz/Billplz-for-WooCommerce#20]
One of the latest features coming from WooCommerce next August 2023 is the `High-Performance Order Storage (HPOS)`.

However, the BillPlz plugging for WooCommerce are not supported this yet. Can you make it compatible with the HPOS functionality? So that I can test it before I use it on my production site?

Details WordPress & WooCommerce.

1. WordPress Version : 6.2.2
2. WooCommerce Version : 7.8.2
3. BillPlz Plugin Version : 3.27.4

Reference :
![image](https://github.com/Billplz/Billplz-for-WooCommerce/assets/47172118/e4604341-6060-470f-97ee-56e3eff17dbd)

**Comment by yiedpozi** [comment]
Thank you for bringing this to our attention. We appreciate your feedback and will take it into consideration for the next update.

**Comment by msulaimanmisri** [comment]
Cool. Thanks @yiedpozi for the hard work
