### ISSUE TITLE
Customise button text "Proceed to Billplz"

### ISSUE THREAD

**Issue by abdusfauzi** [Billplz/Billplz-for-WooCommerce#5]
Hi. Thank you for maintaining this plugin.

Possible to request for custom label for payment button, currently stating `Proceed to Billplz`?

**Comment by wzul** [comment]
Hi.

Fair request. Will work for it soon

**Comment by wzul** [comment]
This feature is now scheduled to be introduced on the next major release in 3.20.0.

Line 121: https://github.com/Billplz/Billplz-for-WooCommerce/blob/master/billplzWoo.php
