### ISSUE TITLE
ID was called incorrectly. Order properties should not be accessed directly.

### ISSUE THREAD

**Issue by abdusfauzi** [Billplz/Billplz-for-WooCommerce#7]
ID was called incorrectly. Order properties should not be accessed directly.

https://github.com/Billplz/Billplz-for-WooCommerce/blob/6ad04b05db66111ec637f5b7240636f7c54ab35e/billplzWoo.php#L525

`$order->ID` change to `$order->get_id()`

**Comment by wzul** [comment]
Intentionally there is a line to correct that matter on the previous line. However, it's careless mistakes that has been done and thank you for pointing it out. Appreciate!

https://github.com/Billplz/Billplz-for-WooCommerce/blob/ae71ff0c34fa90247cb93b243997d83517343f17/billplzWoo.php#L525

**Comment by abdusfauzi** [comment]
@wzul yea! thank you for the super quick respond and update :)

**Comment by abdusfauzi** [comment]
@wzul when can we expect the update to be pushed to wordpress repo? i think you forgot to update the tag?

**Comment by wzul** [comment]
The update is available immediately after this issue is closed. :)

https://plugins.trac.wordpress.org/browser/billplz-for-woocommerce/trunk?rev=1932269
