### ISSUE TITLE
Special do_action hook for this bank type form html. Then, I can redesign the form input myself.

### ISSUE THREAD

**Issue by abdusfauzi** [Billplz/Billplz-for-WooCommerce#8]
Requesting for Special `do_action` hook for this bank type form html. Then, I can redesign the form input myself.

Currently, the form input is in `<select/>` format. However, I'm thinking for providing in **radio button** for my site. So, an action hook over here would be very great.

https://github.com/Billplz/Billplz-for-WooCommerce/blob/1980673910ab25ed658fb5c5277d90d809069dd1/billplzWoo.php#L279-L291

**Comment by abdusfauzi** [comment]
Sample UI https://dribbble.com/shots/3920846-Morning-warm-up-Payment-Option-Card

![dribble](https://cdn.dribbble.com/users/670710/screenshots/3920846/cardwramup04.png)

**Comment by wzul** [comment]
How about action hook `bfw_payment_fields`?

https://github.com/Billplz/Billplz-for-WooCommerce/blob/1980673910ab25ed658fb5c5277d90d809069dd1/billplzWoo.php#L273

**Comment by abdusfauzi** [comment]
@wzul eh. haha. my bad! 👍 thank you for the action hook 🥇
