### ISSUE TITLE
Notice: Undefined index: billplz_bank in /.../plugins/billplz-for-woocommerce/billplzWoo.php on line 185

### ISSUE THREAD

**Issue by abdusfauzi** [Billplz/Billplz-for-WooCommerce#9]
Woops. Got some notice when trying to enable **`Direct to Bank`** feature on development site. Feature not completed?

`Notice: Undefined index: billplz_bank in /.../plugins/billplz-for-woocommerce/billplzWoo.php on line 185`

https://github.com/Billplz/Billplz-for-WooCommerce/blob/03ca4f2d0fa8888720fa63e3c2ff389a912826c3/billplzWoo.php#L184-L186

**Comment by wzul** [comment]
The feature is completed. However, it may suggest that you are customizing the view for the bank selection. Have you pass the billplz_bank parameter?

Or, is there anyway to replicate it?

**Comment by abdusfauzi** [comment]
@wzul steps:
1. install and enable plugin
2. fill up fields with staging keys
3. tick enable **Enable Billplz Auto Submit Feature**
3. Wild error appear! (queue Pokémon music)

**Comment by wzul** [comment]
Weird. I don't found any error message and no error_logs indicating the warning.

https://youtu.be/0cGhY7IaSKE

Did I miss something?

**Comment by abdusfauzi** [comment]
It seems the method `settings_value` loaded and trying to look for the `$_POST` variable.

https://youtu.be/stibtpVc7Ds

**Comment by wzul** [comment]
I'm able to replicate the issue. Thanks!

**Comment by wzul** [comment]
Issue solved on version 3.21.4
